name: Push File

on:
  push:
    branches:
    - main

jobs:
  copy-file:
    name: deploy latest website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes README file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'README.md'
        destination_repo: 'eureka-imagineee-server/eureka-imagineee-server.github.io'
        user_email: 'imagineeelego@gmail.com'
        user_name: 'imagineeeinc'
        commit_message: 'updated site from Eureka server repo'
